#!/usr/bin/env bash

current_branch="$(git rev-parse --abbrev-ref HEAD)"
git checkout main
git branch -D gh-pages
git checkout --orphan gh-pages
git reset
git add -f .nojekyll
git add -f build/html
git commit --author "documentation <docs@build.local>" -m "Add documentation pages"
git push -f origin gh-pages
git checkout -f "${current_branch}"

